api.base.path: /api/v1

oauth.google:
  clientId: google-client-id
  clientSecret: google-client-secret
  redirectUri: http://localhost:8080/authenticate/oauth2callback

security.token.filter.secret: not-a-very-good-secret-but-very-long-very-long

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/life_booster?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
